server:
  port: 9904
spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost/cs544_project
    username: root
    password: "@Adoustar4"
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
logging:
  level:
    root: DEBUG